[package]
name = "swiftrecon"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository = "https://github.com/Devraj192/swift-recon"

[[bin]]
name = "swiftrecon"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
clap_complete.workspace = true
crossterm.workspace = true
ratatui.workspace = true
scraper.workspace = true
serde_json.workspace = true
url.workspace = true
xxhash-rust.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
swiftrecon-core.workspace = true
swiftrecon-scope.workspace = true
swiftrecon-net.workspace = true
swiftrecon-web.workspace = true
swiftrecon-discover.workspace = true
swiftrecon-fingerprint.workspace = true
swiftrecon-report.workspace = true
swiftrecon-engine.workspace = true
swiftrecon-store.workspace = true
mimalloc.workspace = true

[dev-dependencies]
criterion.workspace = true
tempfile.workspace = true

[[bench]]
name = "scan"
harness = false
