[package]
name = "swiftrecon-discover"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
swiftrecon-core.workspace = true
swiftrecon-scope.workspace = true
swiftrecon-net.workspace = true
